create table if not exists public.habit_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  no_sweets boolean not null default false,
  no_coffee boolean not null default false,
  threads_minutes integer,
  no_adult boolean not null default false,
  exercise boolean not null default false,
  morning_walk boolean not null default false,
  evening_walk boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, date)
);

alter table public.habit_entries enable row level security;

drop policy if exists "Users can read own habit entries" on public.habit_entries;
create policy "Users can read own habit entries"
on public.habit_entries for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert own habit entries" on public.habit_entries;
create policy "Users can insert own habit entries"
on public.habit_entries for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update own habit entries" on public.habit_entries;
create policy "Users can update own habit entries"
on public.habit_entries for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own habit entries" on public.habit_entries;
create policy "Users can delete own habit entries"
on public.habit_entries for delete
using (auth.uid() = user_id);

create index if not exists habit_entries_user_date_idx
on public.habit_entries(user_id, date);
